const jsdom = require('jsdom');

const { JSDOM } = jsdom;
const dom = new JSDOM('<div class="vacancy-section"><h2 class="header header_level-2">Ключевые навыки</h2><span data-qa="skills-element" data-tag-id="JavaScript" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="JavaScript"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">JavaScript</span></span></span><span data-qa="skills-element" data-tag-id="jQuery" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="jQuery"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">jQuery</span></span></span><span data-qa="skills-element" data-tag-id="HTML" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="HTML"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">HTML</span></span></span><span data-qa="skills-element" data-tag-id="HTML5" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="HTML5"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">HTML5</span></span></span><span data-qa="skills-element" data-tag-id="CSS" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="CSS"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">CSS</span></span></span><span data-qa="skills-element" data-tag-id="CSS3" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="CSS3"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">CSS3</span></span></span><span data-qa="skills-element" data-tag-id="MySQL" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="MySQL"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">MySQL</span></span></span><span data-qa="skills-element" data-tag-id="Git" class="bloko-tag bloko-tag_inline Bloko-TagList-Tag "><span class="bloko-tag__section bloko-tag__section_text" title="Git"><span class="Bloko-TagList-Text" data-qa="bloko-tag__text">Git</span></span></span></div>');

// const e = dom.window.document.querySelector('vacancy-section');
const alertElem = dom.window.document.querySelectorAll('[data-qa=skills-element]');
console.log(Array.from(alertElem).map(e => e.textContent));
// e.parentNode.removeChild(e);
// console.log(alertElem.innerHTML);
